# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Nicolas Flacco
tagline:          ''
description:      ''
url:              a34729t.github.io

author:
  name:           'Nicolas Flacco'
  url:            xyz

paginate:         3

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/a34729t/a34729t.github.io

pages_list:
  About: '/about'     
  Archive: '/archive'
  Feed: '/atom.xml'

